# --- !Ups

create table "notes" (
    "note_id" bigint generated by default as identity (start with 1) not null primary key,
    "note_type" varchar not null
);

create table "cards" (
    "card_id" bigint generated by default as identity (start with 1) not null primary key,
    "note_id" bigint not null,  -- mark as foreign key later ...
    "front" varchar not null,
    "back" varchar not null
);

create table "users" (
    "user_id" bigint generated by default as identity (start with 1) not null primary key,
    "login" varchar not null,
    "password" varchar
);

create table "progress" (
    "card_id" bigint not null,  -- mark as foreign key later ...
    "interval_seconds" bigint not null default 60,
    "due_at" timestamp not null default current_timestamp,
    "user_id" bigint not null
);

# --- !Downs

drop table "notes";
drop table "cards";
drop table "users";
drop table "progress";
